export const initialCryptoData = [
    {
      id: 1,
      name: 'Bitcoin',
      symbol: 'BTC',
      logo: '/assets/bitcoin.png',
      price: 30000,
      percentChange1h: 0.5,
      percentChange24h: -1.2,
      percentChange7d: 4.5,
      marketCap: '580B',
      volume24h: '35B',
      circulatingSupply: '19M',
      maxSupply: '21M',
      chart: '/assets/bitcoin_chart.png'
    },
    {
      id: 2,
      name: 'Ethereum',
      symbol: 'ETH',
      logo: '/assets/ethereum.png',
      price: 2000,
      percentChange1h: 0.3,
      percentChange24h: -0.8,
      percentChange7d: 3.2,
      marketCap: '240B',
      volume24h: '18B',
      circulatingSupply: '120M',
      maxSupply: '∞',
      chart: '/assets/ethereum_chart.png'
    },
    {
      id: 3,
      name: 'Tether',
      symbol: 'USDT',
      logo: '/assets/tether.png',
      price: 1.00,
      percentChange1h: 0.01,
      percentChange24h: -0.02,
      percentChange7d: 0.05,
      marketCap: '83B',
      volume24h: '45B',
      circulatingSupply: '83B',
      maxSupply: '∞',
      chart: '/assets/tether_chart.png'
    },
    {
      id: 4,
      name: 'BNB',
      symbol: 'BNB',
      logo: '/assets/bnb.png',
      price: 250,
      percentChange1h: 0.4,
      percentChange24h: -1.5,
      percentChange7d: 2.1,
      marketCap: '38B',
      volume24h: '1.2B',
      circulatingSupply: '153M',
      maxSupply: '200M',
      chart: '/assets/bnb_chart.png'
    },
    {
      id: 5,
      name: 'Cardano',
      symbol: 'ADA',
      logo: '/assets/cardano.png',
      price: 0.35,
      percentChange1h: 0.2,
      percentChange24h: -0.6,
      percentChange7d: 1.8,
      marketCap: '12B',
      volume24h: '0.6B',
      circulatingSupply: '35B',
      maxSupply: '45B',
      chart: '/assets/cardano_chart.png'
    },
  ];
  